test post-update

diff --git a/.githooks/post-merge b/.githooks/post-merge
--- a/.githooks/post-merge
+++ b/.githooks/post-merge
@@ -5,5 +5,9 @@
 #
 # To enable this hook, rename this file to "post-merge".
 
-exec git update-server-info
-exec echo "Hello"
+if ! make test 2>&1 ; then
+    echo "111Error while testing the code"
+    exit 1
+fi
+
+exit 0
